"""empty message

Revision ID: 0807054b10ac
Revises: 73d1182f8007
Create Date: 2025-05-15 20:39:16.653830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0807054b10ac'
down_revision = '73d1182f8007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitoring_interval', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('monitoring_interval')

    # ### end Alembic commands ###
