"""empty message

Revision ID: 14e44f9c3535
Revises: e989e17d22e7
Create Date: 2025-05-18 20:43:01.217897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e44f9c3535'
down_revision = 'e989e17d22e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_model', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cpu_cores', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cpu_freq', sa.String(length=255), nullable=True))

    with op.batch_alter_table('monitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_model', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cpu_cores', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cpu_freq', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor_log', schema=None) as batch_op:
        batch_op.drop_column('cpu_freq')
        batch_op.drop_column('cpu_cores')
        batch_op.drop_column('cpu_model')

    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.drop_column('cpu_freq')
        batch_op.drop_column('cpu_cores')
        batch_op.drop_column('cpu_model')

    # ### end Alembic commands ###
