"""Update devices and users add relationshiop

Revision ID: 4c58f5f07a22
Revises: a375a247e20c
Create Date: 2025-05-13 18:45:30.442428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c58f5f07a22'
down_revision = 'a375a247e20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('device_group', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('interval_check', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('type_check', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['serial_number'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_id')
        batch_op.drop_column('type_check')
        batch_op.drop_column('interval_check')
        batch_op.drop_column('device_group')
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
