"""empty message

Revision ID: 73d1182f8007
Revises: 87368913f77c
Create Date: 2025-05-15 15:43:21.358615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73d1182f8007'
down_revision = '87368913f77c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('device_status_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('ser_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ser_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('device_status_ibfk_2', 'users', ['ser_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
