"""Add monitor_log

Revision ID: 74a782bd0f1a
Revises: 4c58f5f07a22
Create Date: 2025-05-13 19:06:48.296997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a782bd0f1a'
down_revision = '4c58f5f07a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitor_log')
    # ### end Alembic commands ###
