"""empty message

Revision ID: 7ef62abb90ce
Revises: 9bfa6bbd8698
Create Date: 2025-05-16 23:35:53.777964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ef62abb90ce'
down_revision = '9bfa6bbd8698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ping_max_response_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ping_min_response_time', sa.Float(), nullable=True))
        batch_op.drop_column('pin_max_response_time')
        batch_op.drop_column('pin_min_response_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_min_response_time', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pin_max_response_time', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('ping_min_response_time')
        batch_op.drop_column('ping_max_response_time')

    # ### end Alembic commands ###
