"""empty message

Revision ID: 87368913f77c
Revises: b7a318873c82
Create Date: 2025-05-15 15:41:58.918842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87368913f77c'
down_revision = 'b7a318873c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ser_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['ser_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ser_id')

    # ### end Alembic commands ###
