"""empty message

Revision ID: 9bfa6bbd8698
Revises: b75db1aabec0
Create Date: 2025-05-16 23:11:54.135601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bfa6bbd8698'
down_revision = 'b75db1aabec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ping_average_response_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ping_max_response_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ping_min_response_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ping_packet_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ping_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('port_status', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('cpu_load', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cpu_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('memmory_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('memmory_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('memory_free', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('memory_available', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('memory_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('disk_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disk_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disk_available', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disk_usage_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disk_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('network_received', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('network_transmitted', sa.Float(), nullable=True))
        batch_op.alter_column('device_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('packet_loss')
        batch_op.drop_column('status')
        batch_op.drop_column('max_response_time')
        batch_op.drop_column('min_response_time')
        batch_op.drop_column('average_response_time')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_login', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('device_password', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('port', sa.String(length=50), nullable=True))
        batch_op.drop_column('interval_check')

    with op.batch_alter_table('monitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ping_average_response_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pin_max_response_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pin_min_response_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ping_packet_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ping_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('port_status', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('cpu_load', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cpu_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('memmory_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('memmory_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('memory_free', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('memory_available', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('memory_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('disk_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disk_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disk_available', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disk_usage_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('disk_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('network_received', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('network_transmitted', sa.Float(), nullable=True))
        batch_op.alter_column('device_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('packet_loss')
        batch_op.drop_column('status')
        batch_op.drop_column('max_response_time')
        batch_op.drop_column('min_response_time')
        batch_op.drop_column('average_response_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_response_time', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('min_response_time', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('max_response_time', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('packet_loss', mysql.FLOAT(), nullable=True))
        batch_op.alter_column('device_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('network_transmitted')
        batch_op.drop_column('network_received')
        batch_op.drop_column('disk_status')
        batch_op.drop_column('disk_usage_percent')
        batch_op.drop_column('disk_available')
        batch_op.drop_column('disk_used')
        batch_op.drop_column('disk_total')
        batch_op.drop_column('memory_status')
        batch_op.drop_column('memory_available')
        batch_op.drop_column('memory_free')
        batch_op.drop_column('memmory_used')
        batch_op.drop_column('memmory_total')
        batch_op.drop_column('cpu_status')
        batch_op.drop_column('cpu_load')
        batch_op.drop_column('port_status')
        batch_op.drop_column('ping_status')
        batch_op.drop_column('ping_packet_loss')
        batch_op.drop_column('pin_min_response_time')
        batch_op.drop_column('pin_max_response_time')
        batch_op.drop_column('ping_average_response_time')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interval_check', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('port')
        batch_op.drop_column('device_password')
        batch_op.drop_column('device_login')

    with op.batch_alter_table('device_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_response_time', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('min_response_time', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('max_response_time', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('packet_loss', mysql.FLOAT(), nullable=True))
        batch_op.alter_column('device_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('network_transmitted')
        batch_op.drop_column('network_received')
        batch_op.drop_column('disk_status')
        batch_op.drop_column('disk_usage_percent')
        batch_op.drop_column('disk_available')
        batch_op.drop_column('disk_used')
        batch_op.drop_column('disk_total')
        batch_op.drop_column('memory_status')
        batch_op.drop_column('memory_available')
        batch_op.drop_column('memory_free')
        batch_op.drop_column('memmory_used')
        batch_op.drop_column('memmory_total')
        batch_op.drop_column('cpu_status')
        batch_op.drop_column('cpu_load')
        batch_op.drop_column('port_status')
        batch_op.drop_column('ping_status')
        batch_op.drop_column('ping_packet_loss')
        batch_op.drop_column('ping_min_response_time')
        batch_op.drop_column('ping_max_response_time')
        batch_op.drop_column('ping_average_response_time')

    # ### end Alembic commands ###
