"""empty message

Revision ID: b75db1aabec0
Revises: 0807054b10ac
Create Date: 2025-05-15 22:13:16.427590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75db1aabec0'
down_revision = '0807054b10ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index('ip_address', ['ip_address'], unique=True)

    # ### end Alembic commands ###
