"""empty message

Revision ID: b7a318873c82
Revises: 29251d1e1a1f
Create Date: 2025-05-15 15:35:02.302671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7a318873c82'
down_revision = '29251d1e1a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('average_response_time', sa.Float(), nullable=True),
    sa.Column('max_response_time', sa.Float(), nullable=True),
    sa.Column('min_response_time', sa.Float(), nullable=True),
    sa.Column('packet_loss', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.drop_table('event_logs')
    op.drop_table('check_results')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_results',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('check_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('result', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('checked_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='check_results_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('event_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('message', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='event_logs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('device_status')
    # ### end Alembic commands ###
