"""empty message

Revision ID: d6ff4fc56171
Revises: 9ad5cd3f3398
Create Date: 2025-05-14 12:02:02.858339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6ff4fc56171'
down_revision = '9ad5cd3f3398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_response_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_response_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_response_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('packet_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=False))
        batch_op.drop_column('response_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_time', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('packet_loss')
        batch_op.drop_column('min_response_time')
        batch_op.drop_column('max_response_time')
        batch_op.drop_column('average_response_time')

    # ### end Alembic commands ###
